import {useState} from "react";
import {useDictation} from "../liquor/useSpeech";
import {saveReviewResponse,LaborApiError,type LaborReview,type ReviewQuestion,type ReviewResponse} from "./api";
import ScheduleComparison from './ScheduleComparison';
const currency=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
const names={adjust:'Yes · try it',consider:'Maybe · check this',keep:'No · keep coverage',data_wrong:'Correct the comparison',ask_owner:'Ask Jon for input'};

export default function ProposalCard({question:q,review,onSaved,number}:{question:ReviewQuestion;review:LaborReview;onSaved:(r:LaborReview)=>void;number:number}){
  const p=q.proposal!;
  const follow=q.followUp;
  const [editing,setEditing]=useState(!q.response),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [choice,setChoice]=useState<ReviewResponse['decision']|null>(q.response?.decision??null);
  const [form,setForm]=useState<ReviewResponse>(q.response??{decision:follow?.originalDecision??'adjust',trial:follow?.previousTrial,context:[],note:'',action:p.action,followUpDate:q.followUpDate,outcome:'',status:'follow_up',proposalId:p.id,proposalVersion:p.version,applicability:'this_shift'});
  const [usedSpeech,setUsedSpeech]=useState('');
  const speech=useDictation();
  const update=(patch:Partial<ReviewResponse>)=>setForm(f=>({...f,...patch,...(patch.note!==undefined&&!patch.note.trim()?{applicability:'this_shift' as const}:{})}));
  const choose=(decision:ReviewResponse['decision'])=>{setChoice(decision);update({decision,action:decision==='keep'||decision==='data_wrong'||decision==='ask_owner'?'':p.action});setError('');};
  const current=p.current.reduce((n,s)=>n+s.endMinute-s.startMinute,0)/60;
  const proposed=p.proposed.reduce((n,s)=>n+s.endMinute-s.startMinute,0)/60;
  const save=async(undo=false)=>{
    setBusy(true);setError('');
    try{onSaved(await saveReviewResponse(review.id,{questionId:q.id,expectedRevision:q.revision,...(undo?{undo:true}:{response:{...form,...(follow&&form.status==='closed'?{outcome:form.note}:{}),proposalId:p.id,proposalVersion:p.version}})}));}
    catch(e){setError(e instanceof LaborApiError&&e.status===409?'A newer answer or proposal is available. Your text is still here; reload after keeping any changes.':'Your answer was not saved. Please retry.');}
    finally{setBusy(false);}
  };
  return <article className="lr-question lr-proposal" aria-labelledby={`q-${q.id}`}>
    <div className="lr-question-header"><div className="lr-question-date"><span className="lr-question-number">{String(number).padStart(2,'0')}</span><time>{new Date(q.date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:'UTC'})} · {p.department==='desk'?'Front desk':p.department==='kitchen'?'Kitchen':'Bar'}</time></div><span className={`lr-badge ${q.response?'lr-badge-saved':''}`}>{q.response?'Answer saved':follow?'Follow-up':'Idea to review'}</span></div>
    <div className="lr-question-content"><h2 id={`q-${q.id}`}>{q.title}</h2><p className="lr-prompt">{q.prompt}</p>
      {follow?<section className="lr-event-check"><strong>Since the earlier review</strong><p>{follow.observation}</p><p className="lr-small">The schedule below is the original idea from {q.date}; it is not a new instruction for the observed date.</p></section>:null}
      <details className={follow?"lr-evidence lr-original-idea":"lr-original-idea lr-original-expanded"} open={!follow}><summary>View original idea and department shifts</summary>
      <section className="lr-why"><h3>Why this came up</h3><div className="lr-comparison-pairs">{p.comparisons.map(c=><div key={c.date+c.period}><span>{new Date(c.date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'})} · {c.period}</span><strong>{currency(c.salesCents)}</strong><span>{c.salesLabel??'GoTab net sales'} · {c.coverage}</span><small>{c.note}</small></div>)}</div><p className="lr-small">{p.summary}</p></section>
      <div className="lr-event-check"><strong>Events and other work checked</strong><p>{p.eventSummary}</p></div>
      {q.knownContext?.length?<div className="lr-event-check"><strong>What you already told us</strong>{q.knownContext.map(c=><p key={c.reviewId+c.questionId}>{c.note||c.outcome||c.action}</p>)}{q.reopenedBecause?<p>New basis: {q.reopenedBecause}</p>:null}</div>:null}
      <section className="lr-candidate"><div className="lr-candidate-heading"><div><p className="lr-kicker">The scheduling idea</p><h3>{Number((current-proposed).toFixed(2))} fewer scheduled hours to test</h3></div><span>{Number(current.toFixed(2))}h → {Number(proposed.toFixed(2))}h</span></div><p>{p.action}</p>{p.worked?<p className="lr-small"><strong>Whole department:</strong> {current.toFixed(2)}h scheduled | {(p.worked.spans.reduce((n,s)=>n+s.endMinute-s.startMinute,0)/60).toFixed(2)}h recorded | {proposed.toFixed(2)}h proposed.</p>:null}{p.impact?<p className="lr-small"><strong>{p.impact.recordedHoursAffected.toFixed(2)} recorded hours</strong> fall in the changed period{p.impact.baseWageIllustrationCents!==null?` | ${currency(p.impact.baseWageIllustrationCents)} scheduled base-wage illustration`:null}. {p.impact.note}</p>:null}<ScheduleComparison proposal={p}/><p className="lr-small">Every changed ordinary shift is at least four hours; unchanged short shifts remain visible. These are scheduled hours; actual savings depend on what is worked.</p></section>
      <details className="lr-evidence"><summary>Evidence and conditions</summary><div className="lr-detail-body"><h3>Would need to be true</h3><ul>{p.conditions.map(c=><li key={c}>{c}</li>)}</ul><h3>Supporting checks</h3><ul>{q.evidence.map(e=><li key={e}>{e}</li>)}</ul><details><summary>Source references</summary><p className="lr-sources">{q.sources.join('; ')}</p></details></div></details>
      </details>
      {!editing&&q.response?<section className="lr-saved"><p className="lr-kicker">Your response</p><h3>{names[q.response.decision]}</h3>{q.response.note?<p>{q.response.note}</p>:null}{q.response.action?<p>{q.response.action}</p>:null}{q.response.applicability==='comparable_shifts'?<p className="lr-small">Remembered for comparable shifts. Staffing targets stay unchanged.</p>:null}{q.response.trial?<p><strong>Trial:</strong> {q.response.trial.state.replaceAll('_',' ')}{q.response.trial.date?' on '+q.response.trial.date:''} ? Service/closing: {q.response.trial.service}</p>:null}{q.response.outcome?<p>Outcome: {q.response.outcome}</p>:null}<div className="lr-actions"><button onClick={()=>setEditing(true)}>Edit / add outcome</button>{q.canUndo?<button disabled={busy} onClick={()=>void save(true)}>Undo last save</button>:null}</div></section>:null}
    </div>
    {editing&&!confirm?<form className="lr-answer" onSubmit={e=>{e.preventDefault();if(!follow&&!choice){setError('Choose Yes, No or Maybe, or correct the comparison.');return;}if(follow&&!form.trial){setError('Choose Tried, Not yet or Stopped.');return;}if(follow?.observedDate&&form.trial?.state==='tried'&&!form.trial.date){setError('Choose the trial date.');return;}if((follow||choice!=='adjust')&&!form.note.trim()){setError('A short reason or condition is enough.');return;}setError('');setConfirm(true);}}>
      {follow?<><h3>What happened with this idea?</h3><div className="lr-proposal-choices" role="group" aria-label="Trial outcome">{(['tried','not_yet','stopped'] as const).map(state=><button key={state} type="button" aria-pressed={form.trial?.state===state} onClick={()=>{setChoice(follow.originalDecision);update({decision:state==='stopped'?'keep':follow.originalDecision,trial:{state,service:form.trial?.service??'unknown',...(state==='tried'&&form.trial?.date?{date:form.trial.date}:{})},status:state==='stopped'?'closed':state==='tried'&&form.trial?.service&&form.trial.service!=='unknown'?'closed':'follow_up',outcome:state==='not_yet'?'':form.note});}}>{state==='tried'?'Tried':state==='not_yet'?'Not yet':'Stopped'}</button>)}</div>{form.trial?.state==='tried'?<><label>When was it tried?<input type="date" required max={new Date().toISOString().slice(0,10)} value={form.trial.date??''} onChange={e=>update({trial:{...form.trial!,date:e.target.value}})}/></label><label>How did service and closing go?<select value={form.trial.service} onChange={e=>update({trial:{...form.trial!,service:e.target.value as 'okay'|'issues'|'unknown'},status:e.target.value==='unknown'?'follow_up':'closed',decision:e.target.value==='issues'?'keep':follow.originalDecision})}><option value="unknown">Not yet checked</option><option value="okay">Work completed; no issue noticed</option><option value="issues">There were issues</option></select></label></>:null}</>:<h3>Would this have worked?</h3>}
      {!follow?<><div className="lr-proposal-choices" role="group" aria-label="Response to the scheduling idea">{(['adjust','keep','consider'] as const).map(value=><button key={value} type="button" aria-pressed={choice===value} onClick={()=>choose(value)}>{value==='adjust'?'Yes':value==='keep'?'No':'Maybe'}</button>)}</div></>:null}
      <label>{follow?'What happened, or what is still needed?':choice==='keep'?'What would the alternative miss?':choice==='consider'?'What would need to be true?':choice==='data_wrong'?'What should we correct?':choice==='ask_owner'?'What do you need Jon to weigh in on?':'Anything we should know? (optional)'}<textarea required={choice!==null&&choice!=='adjust'} rows={choice&&choice!=='adjust'?3:2} maxLength={1600} value={form.note} placeholder={choice==='keep'?'For example, what work needs the extra coverage?':choice==='consider'?'For example, only when training or event work is covered.':'Crew experience, training, events, or other work…'} onChange={e=>update({note:e.target.value,...(follow&&form.trial?.state!=='not_yet'?{outcome:e.target.value}:{})})}/></label>
      {speech.supported?<div className="lr-dictation"><button type="button" className="lr-text-button" onClick={()=>speech.recording?speech.stop():speech.start()}>{speech.recording?'Stop dictation':'Dictate a note'}</button>{speech.transcript&&speech.transcript!==usedSpeech?<><p>{speech.transcript}</p><button type="button" onClick={()=>{update({note:[form.note,speech.transcript].filter(Boolean).join(' ').slice(0,1600)});setUsedSpeech(speech.transcript);}}>Use dictated text</button></>:null}{speech.error?<p>{speech.error} You can type above.</p>:null}</div>:<p className="lr-small">Your phone keyboard’s microphone works here too.</p>}
      {choice==='adjust'||choice==='consider'?<details className="lr-optional"><summary>Adjust the next step <span>Optional</span></summary><label>Next step<textarea rows={3} required={choice==='adjust'} maxLength={600} value={form.action} onChange={e=>update({action:e.target.value})}/></label><label>Check back on<input type="date" required value={form.followUpDate} onChange={e=>update({followUpDate:e.target.value})}/></label></details>:null}
      {(!follow||form.trial?.state==='stopped'||form.trial?.service==='issues')&&form.note.trim()?<fieldset className="lr-optional"><legend>Does this reason apply again?</legend><label className="lr-choice"><input type="radio" name={`scope-${q.id}`} checked={form.applicability!=='comparable_shifts'} onChange={()=>update({applicability:'this_shift'})}/><span>Only this shift</span></label><label className="lr-choice"><input type="radio" name={`scope-${q.id}`} checked={form.applicability==='comparable_shifts'} onChange={()=>update({applicability:'comparable_shifts'})}/><span>Comparable shifts too</span></label><p className="lr-small">A recurring No or correction pauses similar questions for up to six weeks. Changed demand or duties can reopen them. Yes and Maybe remain ideas to follow up.</p></fieldset>:null}
      {!follow?<div className="lr-alt-decisions"><button type="button" className="lr-text-button" onClick={()=>choose('data_wrong')}>The comparison is wrong</button><button type="button" className="lr-text-button" onClick={()=>choose('ask_owner')}>I need Jon’s input</button></div>:null}
      {q.response&&!follow?<div className="lr-outcome"><label>What happened afterward?<textarea rows={2} maxLength={1000} value={form.outcome} onChange={e=>update({outcome:e.target.value})} required={form.status==='closed'}/></label><label className="lr-choice"><input type="checkbox" checked={form.status==='closed'} onChange={e=>update({status:e.target.checked?'closed':'follow_up'})}/><span>Record the outcome and close this idea</span></label></div>:null}
      <div className="lr-actions"><button className="lr-primary" type="submit">Review my response →</button>{q.response?<button type="button" className="lr-text-button" onClick={()=>{setEditing(false);setForm(q.response!);setChoice(q.response!.decision);}}>Cancel edit</button>:null}</div>
    </form>:null}
    {editing&&confirm?<div className="lr-confirm"><h3>Save this next step?</h3><p className="lr-confirm-decision">{follow?`Trial: ${form.trial?.state.replaceAll('_',' ')}`:names[form.decision]}</p>{form.note?<blockquote>{form.note}</blockquote>:null}{form.action?<p>{form.action}</p>:null}{!follow&&form.decision==='consider'?<p className="lr-small">This stays an idea to check, with your condition attached.</p>:null}{!follow&&(form.decision==='adjust'||form.decision==='consider')?<p className="lr-small">Saved in Next schedule. The follow-up email is planned about 90 minutes after the review is complete{review.recapDeliveryEnabled?'.':'; delivery is off for this owner preview.'}</p>:null}{form.applicability==='comparable_shifts'?<p className="lr-small">We’ll reuse your explanation for comparable shifts. Changed demand or operating conditions may warrant a fresh question.</p>:null}{form.outcome?<p>Outcome: {form.outcome}</p>:null}<div className="lr-actions"><button className="lr-primary" disabled={busy} onClick={()=>void save()}>Save response</button><button disabled={busy} onClick={()=>setConfirm(false)}>Back to edit</button></div></div>:null}
    {error?<p className="lr-form-error" role="alert">{error}</p>:null}
    {q.history.length?<details className="lr-history-panel"><summary>Response history ({q.history.length})</summary>{q.history.map(h=><div className="lr-history" key={h.revision}><p className="lr-small">Revision {h.revision} · {new Date(h.createdAt).toLocaleString()}</p><p>{h.response?names[h.response.decision]:'Response reopened'}</p>{h.response?.note?<p>{h.response.note}</p>:null}</div>)}</details>:null}
  </article>;
}
