import test from 'node:test';
import assert from 'node:assert/strict';
import {allowOwnerWrite,recordOwnerResponse} from './live-policy.mjs';
const now=1000000000000;
const trial={mode:'owner-live',commitVerified:true,deadline:new Date(now+60000).toISOString(),code:'OWNERTEST',phone:'3155550101',email:'owner@example.invalid'};
const item={productId:'aea165f3-6f78-4341-9f7d-68a7caab3fa3',quantity:1,cartLineRef:'lane'};
const state=()=>({cartToken:'test-cart',intentIds:new Set(['pi_test_owned']),lineRefs:new Set(['lane'])});
const payment={couponCode:trial.code,items:[item],customer:{phone:'+1 (315) 555-0101',email:trial.email}};
const convert={couponCode:trial.code,items:[item],cartToken:'test-cart',paymentIntentId:'pi_test_owned'};
const check=(path,body,patch={})=>allowOwnerWrite({method:'POST',path,body,trial,state:state(),now,...patch});
test('Allows the designated owner/code only',()=>assert(check('/api/checkout/payment-intents',payment)));
test('Different phone refused before upstream',()=>assert(!check('/api/checkout/payment-intents',{...payment,customer:{...payment.customer,phone:'8155550199'}})));
test('Different confirmation email refused',()=>assert(!check('/api/checkout/payment-intents',{...payment,customer:{...payment.customer,email:'other@example.invalid'}})));
test('Missing/different coupon refused',()=>{for(const couponCode of [undefined,'OTHER'])assert(!check('/api/checkout/payment-intents',{...payment,couponCode}));});
test('Special events/multiple lanes refused',()=>{for(const items of [[{...item,quantity:2}],[{...item,productId:'00000000-0000-0000-0000-000000000000'}],[item,item]])assert(!check('/api/cart/items',items));});
test('Unarmed/expired trials cannot start payment',()=>{assert(!check('/api/checkout/payment-intents',payment,{trial:{...trial,commitVerified:false}}));assert(!check('/api/checkout/payment-intents',payment,{now:now+60001}));});
test('Owned payment converts with its cart/code',()=>assert(check('/api/checkout/convert',convert)));
test('Foreign payment/cart cannot convert',()=>{assert(!check('/api/checkout/convert',{...convert,paymentIntentId:'pi_foreign'}));assert(!check('/api/checkout/convert',{...convert,cartToken:'other'}));});
test('Already-started payment can resolve after test expiry',()=>assert(check('/api/checkout/convert',convert,{now:now+120000})));
test('Recovery grace is bounded',()=>assert(!check('/api/checkout/convert',convert,{now:now+31*60000})));
test('Completed booking prevents another payment',()=>assert(!check('/api/checkout/payment-intents',payment,{state:{...state(),bookingId:'booked'}})));
test('Only this test cart can be released',()=>{assert(allowOwnerWrite({method:'DELETE',path:'/api/cart/items/lane',trial,state:state(),now:now+120000}));assert(!allowOwnerWrite({method:'DELETE',path:'/api/cart/items/foreign',trial,state:state(),now}));});
test('Record response tracks IDs, never a payment secret',()=>{const s=state();recordOwnerResponse({path:'/api/checkout/payment-intents',response:{paymentIntentId:'pi_new',clientSecret:'secret'},state:s});assert(s.intentIds.has('pi_new'));assert(!JSON.stringify(s).includes('secret'));});
