import {readFile,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(process.env.COGS_QA_GALLERY_OUTPUT||fileURLToPath(new URL('./output/',import.meta.url)));
const before=JSON.parse(await readFile(join(root,'before/results.json'),'utf8'));
const after=JSON.parse(await readFile(join(root,'after/results.json'),'utf8'));
const interaction=JSON.parse(await readFile(join(root,'after/interaction-results.json'),'utf8'));
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const names={'home':'Home','food-grid':'Food shelf','food-recording':'Food recording','food-voice-review':'Food speech review','food-voice-resolved':'Food speech choices answered','food-precheck':'Food final questions','food-case-history':'Food case history','food-case-grid':'Food case quantities','liquor-grid':'Liquor count','liquor-voice-review':'Liquor speech review','liquor-precheck':'Liquor final questions','keg-backups':'Backup kegs','keg-empties':'Empty kegs','bottled-beer':'Bottled beer','upload-invoice':'Upload invoice','invoices':'Invoice list','counts':'Count list','price-watch':'Price watch','pour-cost':'Pour cost','pour-cost-detail':'Pour cost expanded','map-pours':'Map pours','recipes':'Recipes','recipe-editor':'Recipe editor','invoice-detail':'Invoice questions','count-detail':'Submitted count','login':'PIN login','teacher-group':'Teacher Group Organizer'};
const cards=after.screens.map(a=>{
  const previous=before.screens.find(s=>s.viewport===a.viewport&&s.name===a.name);
  const img=(stage,s)=>s?`<a href="${stage}/${escape(s.file)}" target="_blank"><img loading="lazy" src="${stage}/${escape(s.file)}" alt="${escape(names[a.name]||a.name)} ${stage} at ${escape(a.viewport)}"></a>`:'<p>Capture unavailable</p>';
  return `<article data-viewport="${escape(a.viewport)}" data-search="${escape((names[a.name]||a.name).toLowerCase())}"><h2>${escape(names[a.name]||a.name)}</h2><div class="pair"><figure><figcaption>Before</figcaption>${img('before',previous)}</figure><figure><figcaption>After</figcaption>${img('after',a)}</figure></div><p class="metric">${a.width} × ${a.height} CSS px · ${a.scrollWidth>a.width?'Horizontal overflow':'No horizontal overflow'}</p></article>`;
}).join('\n');
const totalPassed=after.assertions.length+interaction.checks.length,totalFailed=after.failures.length+interaction.failures.length;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>COGS phone usability review</title><style>
*{box-sizing:border-box}body{margin:0;background:#10121a;color:#eef0f6;font:16px/1.5 system-ui,sans-serif}header,main{max-width:1040px;margin:auto;padding:24px}h1{font-size:clamp(28px,5vw,40px);line-height:1.15;margin:0 0 16px}h2{font-size:22px;margin:0 0 12px}.muted,.metric{color:#bac0d1}.metric{font-size:13px;margin-bottom:0}header{border-bottom:1px solid #393e4c}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0 0}button,input{font:inherit;min-height:44px;border:1px solid #676e86;border-radius:8px;background:#222734;color:#fff;padding:10px 14px}button{cursor:pointer}button[aria-pressed=true]{background:#66e0bd;color:#08251d;border-color:#66e0bd}input{flex:1;min-width:200px}article{background:#191d29;border:1px solid #363d50;border-radius:12px;padding:18px;margin:0 0 24px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;min-width:0}figcaption{font-size:14px;font-weight:700;color:#bac0d1;margin:0 0 8px}img{display:block;width:100%;height:auto;border-radius:8px;border:1px solid #3f4355}a{color:#83e8ce}article[hidden]{display:none}.stats{display:flex;gap:12px;flex-wrap:wrap}.stats span{background:#222734;border-radius:8px;padding:10px 14px}footer{padding:16px 0 30px;color:#bac0d1;font-size:14px}@media(max-width:560px){header,main{padding:16px}.pair{grid-template-columns:1fr;gap:18px}article{padding:12px}h2{font-size:19px}}
</style></head><body><header><h1>COGS phone usability review</h1><p>Inventory screens with sample counts, speech questions and review data. Current-main integration review.</p><p class="muted">The Samsung-sized view uses 412 × 915 CSS pixels; the narrower phone uses 360 × 800. This is browser emulation with synthetic audio and API responses. Actual Android keyboard and phone microphone checks remain separate.</p><div class="stats"><span>${before.screens.length} before captures</span><span>${after.screens.length} after captures</span><span>${totalPassed} updated-UI checks passed</span><span>${totalFailed} checks failed</span></div><div class="controls"><button data-view="s24-ultra" aria-pressed="true">Samsung-sized phone</button><button data-view="small-phone" aria-pressed="false">Narrower phone</button><button data-view="desktop" aria-pressed="false">Desktop</button><input type="search" aria-label="Filter screens" placeholder="Find a screen"></div></header><main>${cards}<footer><p>Additional examples: <a href="after/s24-ultra-voice-safety.png">Missing spoken quantity and package unit</a> · <a href="after/s24-ultra-narrative-findings.png">Narrative findings with shelf evidence</a>.</p><p>All API responses are local fixtures. No real inventory, upload, email, recording, transcription or LLM call was made.</p></footer></main><script>
let viewport='s24-ultra';const search=document.querySelector('input');const update=()=>{for(const card of document.querySelectorAll('article'))card.hidden=card.dataset.viewport!==viewport||!card.dataset.search.includes(search.value.toLowerCase())};for(const button of document.querySelectorAll('[data-view]'))button.addEventListener('click',()=>{viewport=button.dataset.view;for(const other of document.querySelectorAll('[data-view]'))other.setAttribute('aria-pressed',String(other===button));update()});search.addEventListener('input',update);update();
</script></body></html>`;
await writeFile(join(root,'index.html'),html);
console.log('Paired screenshot gallery:',join(root,'index.html'));
