import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {join,resolve} from 'node:path';
const {JSDOM}=process.env.COGS_QA_DEPS?createRequire(join(resolve(process.env.COGS_QA_DEPS),'package.json'))('jsdom'):await import('jsdom');
const bundle=await readFile(new URL('./dist/fixture.js',import.meta.url),'utf8'),pause=()=>new Promise(r=>setTimeout(r,20));
async function until(check,what){for(let i=0;i<200;i++){if(check())return;await pause();}throw Error(`${what} timed out`);}
let passed=0;
const id='00000000-0000-0000-0000-000000000041',costQuery=`view=foodrecipes&sku=${id}&review=cost`;
async function scenario(name,query,test){const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:`http://localhost/cogs/?${query}`,runScripts:'outside-only',pretendToBeVisual:true});dom.window.Response=Response;
 try{dom.window.eval(bundle);const doc=dom.window.document,text=()=>doc.body.textContent.replace(/\s+/g,' '),button=name=>[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()===name);
 const click=async name=>{const b=button(name);assert.ok(b,`button ${name}`);assert.ok(!b.disabled,`enabled ${name}`);b.click();await pause();};
 const type=async(el,value)=>{assert.ok(el,'input exists');const proto=el.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));await pause();};
 await until(()=>doc.querySelector('h1,h2'),'app bootstrap');await test({dom,doc,text,button,click,type,qa:dom.window.foodCostQa});passed++;console.log(`PASS ${name}`);
 }finally{dom.window.close();}}
async function enterCost(t,value='20'){await t.type(t.doc.querySelector('[aria-label="Current physical unit cost"]'),value);await t.type(t.doc.querySelector('[aria-label="Cost confirmation reason"]'),'Verified invoice price for a case of four fifty ounce bags');}
let correctionHref;
await scenario('actual inbox correction targets exact food SKU and current cost review','view=opsinbox',async t=>{await until(()=>t.doc.querySelector('a[href*="review=cost"]'),'inbox link');correctionHref=t.doc.querySelector('a[href*="review=cost"]').getAttribute('href');assert.equal(correctionHref,`/cogs/?${costQuery}`);assert.match(t.text(),/Impact unknown/);assert.doesNotMatch(t.text(),/All checked sources are clear/);});
await scenario('inbox cost deep link survives PIN and selects exact same-name SKU',`${correctionHref.split('?')[1]}&pin=1`,async t=>{await until(()=>t.button('Enter'),'PIN');for(const key of ['1','2','3','4'])await t.click(key);await t.click('Enter');await until(()=>t.doc.activeElement?.getAttribute('data-cost-sku')===id,'cost target focus');assert.equal(t.doc.querySelector('[data-cost-sku]').getAttribute('data-cost-sku'),id);assert.equal(t.dom.window.location.search,'');assert.match(t.text(),/Cost held:.*different count unit or package/);assert.match(t.text(),/One count unit contains 200 oz/);assert.equal(t.qa.calls.filter(c=>c.path.endsWith('/pin-login')).length,1);});
await scenario('recipe cost stays unknown until explicitly confirmed current case price',costQuery,async t=>{await until(()=>t.button('Case cheese dip'),'recipe');await t.click('Case cheese dip');assert.match(t.text(),/Partial ingredient cost/);assert.doesNotMatch(t.text(),/Ingredient cost \$1\.00/);await enterCost(t);assert.ok(t.button('Confirm current-unit cost').disabled);t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').click();await pause();await t.click('Confirm current-unit cost');await until(()=>t.text().includes('Ingredient cost $1.00'),'complete reviewed cost');assert.doesNotMatch(t.text(),/Cost held:/);const saved=t.qa.calls.find(c=>c.path.endsWith('/food-cost'));assert.equal(saved.body.costPerCountUnit,20);assert.equal(saved.body.expectedUnitsPerCase,4);assert.equal(saved.body.expectedUnitLabel,'case');assert.equal(saved.body.expectedRevision,'a'.repeat(64));assert.equal(saved.body.physicalBasisConfirmed,true);assert.match(t.text(),/recorded in the cost ledger/);assert.equal(t.qa.calls.filter(c=>c.method==='PATCH').length,1);});
await scenario('ordinary staff can read the cost hold but cannot confirm a price',`${costQuery}&admin=0`,async t=>{await until(()=>t.doc.querySelector('[data-cost-sku]'),'staff cost panel');assert.match(t.text(),/Cost held:/);assert.ok(t.doc.querySelector('[aria-label="Ingredient cost confirmation"] fieldset').disabled);assert.equal(t.qa.calls.filter(c=>c.method==='PATCH').length,0);});
await scenario('unsupported precision and changed price require renewed physical confirmation',costQuery,async t=>{await until(()=>t.button('Confirm current-unit cost'),'cost editor');await enterCost(t,'20.1234567');t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').click();await pause();assert.ok(t.button('Confirm current-unit cost').disabled);await t.type(t.doc.querySelector('[aria-label="Current physical unit cost"]'),'20.123456');assert.ok(!t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').checked);assert.ok(t.button('Confirm current-unit cost').disabled);assert.equal(t.qa.calls.filter(c=>c.method==='PATCH').length,0);});
await scenario('stale cost save keeps the hold and reason; reload displays new physical basis',`${costQuery}&mode=stale`,async t=>{await until(()=>t.button('Confirm current-unit cost'),'cost editor');await enterCost(t);t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').click();await pause();await t.click('Confirm current-unit cost');await until(()=>t.text().includes('Reload before confirming cost.'),'stale guard');assert.match(t.text(),/Cost held:/);assert.equal(t.doc.querySelector('[aria-label="Cost confirmation reason"]').value,'Verified invoice price for a case of four fifty ounce bags');await t.click('Reload recipe book');await until(()=>t.text().includes('One count unit contains 400 oz'),'current basis');assert.ok(!t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').checked);assert.equal(t.qa.calls.filter(c=>c.method==='PATCH').length,1);});
for(const mode of ['capacity-held','null-result','missing-result'])await scenario(`${mode} cannot announce confirmed cost`,`${costQuery}&mode=${mode}`,async t=>{await until(()=>t.button('Confirm current-unit cost'),'cost editor');await enterCost(t);t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').click();await pause();await t.click('Confirm current-unit cost');await until(()=>t.text().includes('Review the current physical capacity or container contents'),'physical hold');assert.match(t.text(),/Cost held:/);assert.doesNotMatch(t.text(),/Current-unit cost confirmed and recorded/);assert.equal(t.qa.calls.filter(c=>c.method==='PATCH').length,1);});
await scenario('a usable confirmed zero cost is accepted as complete',costQuery,async t=>{await until(()=>t.button('Case cheese dip'),'recipe');await t.click('Case cheese dip');await enterCost(t,'0');t.doc.querySelector('[aria-label="Current physical unit cost confirmed"]').click();await pause();await t.click('Confirm current-unit cost');await until(()=>t.text().includes('Current-unit cost confirmed and recorded'),'usable zero');assert.match(t.text(),/Ingredient cost \$0\.00/);assert.doesNotMatch(t.text(),/Cost held:/);});
console.log(`${passed} food physical cost UI scenarios passed`);
