import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {browser} from '../qa-cogs-mobile/cdp.mjs';
const b=await browser(),results=[];
const fixture=()=>{
  const calls=[],packages=[{id:'pack',revision:1,name:'QA wine',skuId:'sku',category:'wine',capacityOz:640,countUnitsPerKeg:1,countUnit:'case',unitLabel:null,transactionName:'Wine 4',zoneId:'wall',productId:'18468666',effectiveFrom:'2026-01-01T00:00:00Z',backupName:'QA wine keg',active:true}],observations=[],links=[];
  const kitchen={staleNext:false,reloadFailNext:false};window.__beverageQa={calls,kitchen};
  window.fetch=async(url,init={})=>{const path=new URL(url,location.href).pathname.replace(/\/$/,''),body=init.body?JSON.parse(init.body):null,method=init.method||'GET';calls.push({path,method,body});let payload,status=200;
    if(path.endsWith('/tap-inventory'))payload={packages,observations,reports:[],items:[],counts:[{id:'walk',startedAt:new Date(Date.now()-600000).toISOString(),submittedAt:null,status:'draft',countedBy:'qa'}]};
    else if(path.endsWith('/tap-observations')&&method==='POST'){payload={id:'obs',revision:1,observedAt:'2026-10-03T20:00:00Z',status:'draft',lines:[],countedBy:'qa',submittedAt:null,boundaryCountSessionId:body?.boundaryCountSessionId ?? null,samePhysicalWalkConfirmed:body?.samePhysicalWalkConfirmed ?? false};observations.push(payload);}
    else if(path.endsWith('/tap-observations/obs')&&method==='PUT'){payload={...observations[0],revision:observations[0].revision+1,lines:body.lines.map(l=>({...l,package:packages[0],remainingOz:l.method==='measured_ounces'?l.remaining:l.remaining*640,costPerKegCents:12000,costBasis:'last',note:null}))};observations[0]=payload;}
    else if(path.endsWith('/tap-observations/obs/submit')){payload={...observations[0],status:'submitted',submittedAt:'2026-10-03T20:05:00Z'};observations[0]=payload;}
    else if(path.endsWith('/beverage-cost'))payload={reports:[],counts:{liquor:[],packaged_beer:[]},allIn:[{periodStart:'2026-09-01',periodEnd:'2026-10-01',cogsCents:null,salesCents:null,pct:null,targetPct:19,reasons:['measured_tap_bracket_does_not_match'],sources:{}}]};
    else if(path.endsWith('/consumable-recipes'))payload={recipes:[],items:[]};
    else if(path.endsWith('/kitchen-boundaries')){if(kitchen.reloadFailNext){kitchen.reloadFailNext=false;status=503;payload={error:'Source temporarily unavailable'};}else payload={foodCounts:[{id:'food-walk',countedBy:'qa',startedAt:'2026-10-03T17:00:00Z',submittedAt:'2026-10-03T19:00:00Z',section:'food',isFullCount:true,status:'submitted'}],barCounts:[{id:'bar-walk',countedBy:'qa',startedAt:'2026-10-03T18:00:00Z',submittedAt:'2026-10-03T20:00:00Z',section:'bar',isFullCount:true,status:'submitted'}],links,policy:'Original measurement times stay recorded.'};}
    else if(path.endsWith('/kitchen-boundaries/bar-walk')&&method==='POST'){if(kitchen.staleNext){kitchen.staleNext=false;links.splice(0,links.length,{...links[0],revision:links[0].revision+1,reason:'Another admin reviewed this link'});}if(body.revision!==(links[0]?.revision??0)){status=409;payload={error:'stale_kitchen_boundary_revision'};}else{payload={link:{barCountId:'bar-walk',foodCountId:body.foodCountId,active:body.active,revision:body.revision+1,reason:body.reason,snapshot:{foodSubmittedAt:'2026-10-03T19:00:00Z',barSubmittedAt:'2026-10-03T20:00:00Z'}}};links.splice(0,links.length,payload.link);}}
    else{status=503;payload={error:`Unmocked QA request: ${path}`};}
    return new Response(JSON.stringify(payload),{status,headers:{'Content-Type':'application/json'}});
  };
};
await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`(${fixture.toString()})()`});
const pause=()=>new Promise(r=>setTimeout(r,80));
async function click(text){await b.until(`[...document.querySelectorAll('button')].some(e=>e.textContent.trim().includes(${JSON.stringify(text)}))`);await b.evaluate(`(()=>{const e=[...document.querySelectorAll('button')].find(e=>e.textContent.trim().includes(${JSON.stringify(text)}));if(e.disabled)throw Error('disabled button '+${JSON.stringify(text)});e.click()})()`);await pause();}
async function input(label,value,select=false){await b.evaluate(`(()=>{const e=[...document.querySelectorAll('label')].find(e=>e.childNodes[0]?.textContent.includes(${JSON.stringify(label)}))?.querySelector(${JSON.stringify(select?'select':'input')});if(!e)throw Error('missing label '+${JSON.stringify(label)});Object.getOwnPropertyDescriptor(${select?'HTMLSelectElement':'HTMLInputElement'}.prototype,'value').set.call(e,${JSON.stringify(String(value))});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await pause();}
try{for(const width of [360,412,1280]){
  await b.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<500});await b.send('Page.navigate',{url:'http://127.0.0.1:4351/'});await b.until(`document.querySelector('h2')?.textContent==='Tap inventory'`);await b.until(`document.querySelector('select option[value=walk]')`);
  await input('Accounting boundary','walk',true);await b.evaluate(`[...document.querySelectorAll('label')].find(e=>e.textContent.includes('same physical bar counting walk')).querySelector('input').click()`);await pause();await input('Reason for the saved observation','Observed the stock independently');await click('Start observation');await click('Add stock location');await input('Unique tap or backup location name','tap 4');await input('Reviewed product and package','pack',true);await input('Remaining ounces','0');await click('Save draft');await b.until(`document.querySelector('h3')?.textContent.includes('Observation · v2')`);
  await click('Cost QA');await b.until(`document.querySelector('h2')?.textContent==='Beverage cost'`);assert.match(await b.evaluate(`document.querySelector('.lq-bv').innerText`),/Unknown · target 19%/);
  await b.until(`document.querySelector('select option[value="bar-walk"]')`);await b.evaluate(`[...document.querySelectorAll('summary')].find(e=>e.textContent.includes('Link kitchen produce')).click()`);await input('Full bar count','bar-walk',true);await input('Food count from this physical walk','food-walk',true);await input('Reason for kitchen boundary link','Reviewed the same physical walk');assert.equal(await b.evaluate(`[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Save link and version')).disabled`),true);await b.evaluate(`document.querySelector('[aria-label="Confirm food and bar same physical walk"]').click()`);await pause();await click('Save link and version both neighbors');await b.until(`document.querySelector('.lq-bv').innerText.includes('Saved link v1')`);assert.match(await b.evaluate(`document.querySelector('.lq-bv').innerText`),/Actual food submit/);
  const details=await b.evaluate("Array.from(document.querySelectorAll('a')).filter(a=>a.textContent.includes('count details')).map(a=>({label:a.textContent,href:a.getAttribute('href'),target:a.target}))");assert.deepEqual(details,[{label:'Open bar count details',href:'?view=counts&section=bar&count=bar-walk',target:'_blank'},{label:'Open food count details',href:'?view=counts&section=food&count=food-walk',target:'_blank'}]);
  assert.match(await b.evaluate("document.querySelector('.lq-bv').innerText"),/Bar walk:[\s\S]*Food walk:/);
  assert.equal(await b.evaluate("[...document.querySelectorAll('a')].filter(a=>a.textContent.includes('count details')).every(a=>a.getBoundingClientRect().top>=a.parentElement.previousElementSibling.getBoundingClientRect().bottom)"),true,'Count details must not overlap walk ranges');
  await input('Reason for kitchen boundary link','Checked both physical walks after the other review');await b.evaluate("document.querySelector('[aria-label=\"Confirm food and bar same physical walk\"]').click();window.__beverageQa.kitchen.staleNext=true");await pause();await click('Save link and version both neighbors');await b.until("document.querySelector('[role=alert]')?.textContent.includes('Reload count links')");
  assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Reason for kitchen boundary link\"]').value"),'Checked both physical walks after the other review');assert.equal(await b.evaluate("[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Save link and version')).disabled"),true);
  await b.evaluate("window.__beverageQa.kitchen.reloadFailNext=true");await click('Reload count links');await b.until("document.querySelector('[role=alert]')?.textContent.includes('could not be reloaded')");assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Reason for kitchen boundary link\"]').value"),'Checked both physical walks after the other review');assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Full bar count for kitchen link\"]').value"),'bar-walk');assert.equal(await b.evaluate("[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Save link and version')).disabled"),true);
  await click('Reload count links');await b.until("document.querySelector('.lq-bv').innerText.includes('Saved link v2')");assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Reason for kitchen boundary link\"]').value"),'Checked both physical walks after the other review');assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Food count for kitchen link\"]').value"),'food-walk');assert.equal(await b.evaluate("document.querySelector('[aria-label=\"Confirm food and bar same physical walk\"]').checked"),false);assert.equal(await b.evaluate("[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Save link and version')).disabled"),true);
  await b.evaluate("document.querySelector('[aria-label=\"Confirm food and bar same physical walk\"]').click()");await pause();await click('Save link and version both neighbors');await b.until("document.querySelector('.lq-bv').innerText.includes('Saved link v3')");const kitchenCalls=await b.evaluate("window.__beverageQa.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/kitchen-boundaries/bar-walk'))");assert.deepEqual(kitchenCalls.map(c=>c.body.revision),[0,1,2]);assert.equal(kitchenCalls[2].body.reason,'Checked both physical walks after the other review');
  await mkdir(new URL('./output/',import.meta.url),{recursive:true});const kitchenScreenshot=await b.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(new URL('./output/kitchen-'+width+'.png',import.meta.url),Buffer.from(kitchenScreenshot.data,'base64'));
  await click('Tap QA');await b.until(`[...document.querySelectorAll('button')].some(e=>e.textContent.includes('draft · v2'))`);await click('draft · v2');assert.equal(await b.evaluate(`[...document.querySelectorAll('label')].find(e=>e.childNodes[0]?.textContent==='Remaining ounces').querySelector('input').value`),'0');
  await input('Reason for the saved observation','Reviewed the saved observations');await click('Review before submit');await click('Save and submit');await b.until(`document.querySelector('h3')?.textContent.includes('Correction · v3')`);
  const calls=await b.evaluate('window.__beverageQa.calls');assert.equal(calls.filter(c=>c.path.endsWith('/submit')).length,1);assert.equal(calls.find(c=>c.method==='PUT').body.lines[0].remaining,0);assert.equal(calls.find(c=>c.path.endsWith('/tap-observations')).body.samePhysicalWalkConfirmed,true);assert.equal(calls.find(c=>c.path.endsWith('/tap-observations')).body.boundaryCountSessionId,'walk');assert.match(await b.evaluate(`document.querySelector('.lq-bv').innerText`),/retain this measurement time/);assert.equal(await b.evaluate('document.documentElement.scrollWidth>innerWidth+1'),false,`page overflow ${width}`);
  await mkdir(new URL('./output/',import.meta.url),{recursive:true});const screenshot=await b.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(new URL(`./output/tap-${width}.png`,import.meta.url),Buffer.from(screenshot.data,'base64'));
  assert.equal(calls.find(c=>c.path.endsWith('/kitchen-boundaries/bar-walk')).body.confirmed,true);assert.equal(calls.find(c=>c.path.endsWith('/kitchen-boundaries/bar-walk')).body.foodCountId,'food-walk');results.push({width,explicitZeroSaved:true,reopened:true,reviewedSubmittedOnce:true,unmatchedAllInUnknown:true,coordinatedWalkExplicitlyConfirmed:true,kitchenLinkExplicitlyConfirmed:true,kitchenFreshRevisionAfter409:true,kitchenFailedReloadPreservesDraft:true,kitchenReasonRetained:true,kitchenCountDetailLinks:true,measurementTimeRetained:true,overflow:false});
}assert.equal(b.blocked.length,0,JSON.stringify(b.blocked));await writeFile(new URL('./output/results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await b.close();}
