/**
 * /sitemap-videos.xml — Google video sitemap extension.
 *
 * Per the 2026-05-17 Google docs audit, the video sitemap is the
 * canonical discovery surface for video search when a site has many
 * videos. Lives alongside the main `sitemap-index.xml` (generated by
 * `@astrojs/sitemap`) and is referenced from `public/robots.txt`.
 *
 * Schema reference:
 *   https://developers.google.com/search/docs/crawling-indexing/sitemaps/video-sitemaps
 *
 * Per Google's spec:
 *   - `<video:duration>` is **seconds** as an integer (NOT ISO 8601 —
 *     that's only the JSON-LD form).
 *   - `<video:publication_date>` is ISO 8601 W3C Datetime — date with
 *     timezone offset is the canonical form (e.g. `2026-04-15T00:00:00-06:00`).
 *   - `<video:expiration_date>` for seasonal videos. Google drops the
 *     entry past this date.
 *
 * One `<url>` per video — its `<loc>` is the primary page that owns
 * the video. Multiple videos pointing at the same `<loc>` are allowed;
 * Google merges them under the same page.
 *
 * Astro `prerender = true` writes this to `dist/client/sitemap-videos.xml`
 * at build time. Static file; no server runtime cost.
 */

import type { APIRoute } from "astro";
import {
  VIDEO_REGISTRY,
  thumbnailUrl,
  contentUrl,
  primaryPageUrl,
} from "../data/videos";

export const prerender = true;

// XML-escape strings going into element bodies. The description field
// is the most likely source of `&` (entity references) — but covering
// all five XML special chars is cheap and worth the belt-and-suspenders.
function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// Twisted Pin is in Plainfield, IL — US Central time. ISO 8601 W3C
// Datetime format with timezone offset is what Google's spec requires.
const TZ_OFFSET = "-06:00";

export const GET: APIRoute = () => {
  const entries = VIDEO_REGISTRY.map((v) => {
    const expirationLine = v.expires
      ? `\n      <video:expiration_date>${v.expires}T23:59:59${TZ_OFFSET}</video:expiration_date>`
      : "";

    return `  <url>
    <loc>${primaryPageUrl(v)}</loc>
    <video:video>
      <video:thumbnail_loc>${thumbnailUrl(v)}</video:thumbnail_loc>
      <video:title>${escapeXml(v.name)}</video:title>
      <video:description>${escapeXml(v.description)}</video:description>
      <video:content_loc>${contentUrl(v)}</video:content_loc>
      <video:duration>${v.durationSeconds}</video:duration>
      <video:publication_date>${v.uploadDate}T00:00:00${TZ_OFFSET}</video:publication_date>${expirationLine}
    </video:video>
  </url>`;
  }).join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
${entries}
</urlset>
`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
};
