import { useEffect,useState } from "react";
import { getConsumableRecipes,saveConsumableRecipe,type ConsumableData,type ConsumableRecipe } from "../beverage-api";
const beverageMoney=(cents:number|null)=>cents==null ? "Unknown" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
export default function ConsumableRecipes({canManage}:{canManage:boolean}) {
  const [data,setData]=useState<ConsumableData|null>(null),[productId,setProductId]=useState(""),[revision,setRevision]=useState(0),[lines,setLines]=useState<ConsumableRecipe["lines"]>([]),[basis,setBasis]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>setData(await getConsumableRecipes());useEffect(()=>{load().catch(e=>setError(String(e)));},[]);
  const open=(r:ConsumableRecipe)=>{setProductId(r.productId);setRevision(r.revision);setLines(r.lines);setBasis(r.basis);};
  return <details className="lq-bv-card"><summary>Verified cocktail consumables</summary><p>Record approved garnish, mixer and other consumable quantities. Missing yields or prices stay unknown. These costs are an adjunct to the spirit recipe.</p>{error && <p role="alert">{error}</p>}
    {data?.recipes.map(r=><div key={r.productId} className="lq-bv-row"><button className="lq-btn" onClick={()=>open(r)}>{r.productId} · v{r.revision}</button><span>{beverageMoney(r.cost.completeCents)}{r.cost.missing.length ? ` · ${r.cost.missing.length} unpriced or unconverted` : ""}</span></div>)}
    {canManage && <><button className="lq-btn" onClick={()=>{setProductId("");setRevision(0);setLines([]);setBasis("");}}>New consumable recipe</button><label>Exact GoTab product ID<input value={productId} disabled={revision>0} onChange={e=>setProductId(e.target.value)}/></label>
      {lines.map((line,i)=><fieldset key={i}><label>Ingredient<select value={line.skuId} onChange={e=>{const s=data?.items.find(s=>s.id===e.target.value);setLines(lines.map((l,j)=>i===j ? {...l,skuId:e.target.value,unit:s?.recipeUnit ?? s?.countUnit ?? ""} : l));}}><option value="">Choose…</option>{data?.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Approved quantity<input type="number" min="0.0001" step="0.0001" value={line.qty} onChange={e=>setLines(lines.map((l,j)=>i===j ? {...l,qty:Number(e.target.value)} : l))}/></label><label>Unit<input value={line.unit} onChange={e=>setLines(lines.map((l,j)=>i===j ? {...l,unit:e.target.value} : l))}/></label><button className="lq-btn" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Remove</button></fieldset>)}
      <button className="lq-btn" onClick={()=>setLines([...lines,{skuId:"",qty:1,unit:""}])}>Add consumable</button><label>Source or approved physical basis<textarea value={basis} onChange={e=>setBasis(e.target.value)}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="lq-btn" disabled={busy || !productId || basis.trim().length<3 || reason.trim().length<3} onClick={async()=>{setBusy(true);setError("");try{await saveConsumableRecipe(productId,{revision,lines,basis,reason});await load();setRevision(revision+1);}catch(e){setError(String(e));}finally{setBusy(false);}}}>Save audited recipe</button>
    </>}
  </details>;
}
