import { useEffect,useState } from "react";
import { addTapPackage,computeTapReport,getTapInventory,saveTapObservation,startTapObservation,submitTapObservation,type TapData,type TapEntry,type TapObservation } from "../beverage-api";
import { BeverageReportView } from "./BeverageCost";
import "../beverage.css";
export function tapEntries(row:TapObservation):TapEntry[] {return row.lines.map(l=>({key:l.key,stockKind:l.stockKind,packageId:l.package.id,method:l.method,remaining:l.method==="measured_ounces" ? l.remainingOz : l.remainingOz/l.package.capacityOz,note:l.note}));}
const blank=():TapEntry=>({key:"",stockKind:"tap",packageId:"",remaining:0,method:"measured_ounces"});
export default function TapInventory({onDone,canManage,canCount=true}:{onDone:()=>void;canManage:boolean;canCount?:boolean}) {
  const [data,setData]=useState<TapData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reason,setReason]=useState(""),[open,setOpen]=useState<TapObservation|null>(null),[entries,setEntries]=useState<TapEntry[]>([]),[review,setReview]=useState(false),[history,setHistory]=useState(false);
  const [mapping,setMapping]=useState({name:"",skuId:"",category:"beer" as "beer"|"wine",capacityOz:"",countUnitsPerKeg:"",transactionName:"",zoneId:"",backupName:"",effectiveFrom:new Date().toISOString().slice(0,16),active:true});
  const [boundaryCountSessionId,setBoundaryCountSessionId]=useState(""),[sameWalk,setSameWalk]=useState(false);
  const load=async()=>setData(await getTapInventory());useEffect(()=>{load().catch(e=>setError(String(e)));},[]);
  const work=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await fn();await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
  const edit=(row:TapObservation)=>{setOpen(row);setEntries(tapEntries(row));setReview(false);};
  const change=(i:number,patch:Partial<TapEntry>)=>{setEntries(entries.map((e,j)=>j===i ? {...e,...patch} : e));setReview(false);};
  const canEdit=open?.status==="submitted" ? canManage : canCount;
  const rows=data?.reports ?? [],latest=rows.filter(r=>!rows.some(o=>o.scope===r.scope && o.closingId===r.closingId && o.version>r.version));
  return <section className="lq-bv"><button className="lq-btn" onClick={onDone}>Back</button><h2>Tap inventory</h2><p>Observe full backup kegs and tapped contents separately. Measure ounces, or label an observed fraction as an estimate. POS sales never fill in the remaining stock.</p>
    {error && <p role="alert">{error}</p>}{!data && !error && <p>Loading…</p>}
    <label>Reason for the saved observation, correction or report<input value={reason} onChange={e=>setReason(e.target.value)}/></label>
    {canCount && <><label>Accounting boundary<select value={boundaryCountSessionId} onChange={e=>{setBoundaryCountSessionId(e.target.value);setSameWalk(false);}}><option value="">Independent tap observation</option>{(data?.counts ?? []).filter(c=>Date.now()-new Date(c.startedAt).getTime()<=86_400_000).map(c=><option key={c.id} value={c.id}>Current bar counting walk · {new Date(c.startedAt).toLocaleString()}</option>)}</select></label>{boundaryCountSessionId && <label><input type="checkbox" checked={sameWalk} onChange={e=>setSameWalk(e.target.checked)}/> I am observing the tap wall during this same physical bar counting walk. Complete a full bar count within one day.</label>}<button className="lq-btn" disabled={busy || (!!boundaryCountSessionId && !sameWalk)} onClick={()=>work(async()=>edit(await startTapObservation({boundaryCountSessionId:boundaryCountSessionId || null,samePhysicalWalkConfirmed:sameWalk})))}>Start observation</button></>}
    {data?.observations.map(row=><div className="lq-bv-row" key={row.id}><button className="lq-btn" onClick={()=>edit(row)}>{new Date(row.observedAt).toLocaleString()} · {row.status} · v{row.revision}</button>{row.status==="submitted" && canManage && <><button className="lq-btn" disabled={busy || reason.trim().length<3} onClick={()=>work(()=>computeTapReport(row.id,"tap_measured",reason))}>Compare actual with pours</button><button className="lq-btn" disabled={busy || reason.trim().length<3} onClick={()=>work(()=>computeTapReport(row.id,"draft_estimate",reason))}>13-week draft estimate</button></>}</div>)}
    {open && <div className="lq-bv-card"><h3>{open.status==="submitted" ? "Correction" : "Observation"} · v{open.revision}</h3><p>Actually observed {new Date(open.observedAt).toLocaleString()}. Missing is unknown; enter an explicit zero after looking.</p>{open.boundaryCountSessionId && <p>Confirmed same bar counting walk. Reports use that full count's submission as the shared accounting boundary and retain this measurement time. Submit the full bar count before computing reports.</p>}
      {entries.map((entry,i)=><fieldset key={i}><legend>Stock location {i+1}</legend><label>Unique tap or backup location name<input disabled={!canEdit || busy} value={entry.key} onChange={e=>change(i,{key:e.target.value})}/></label>
        <label>Reviewed product and package<select disabled={!canEdit || busy} value={entry.packageId} onChange={e=>change(i,{packageId:e.target.value})}><option value="">Choose…</option>{data?.packages.filter(p=>p.active || p.id===entry.packageId).map(p=><option key={p.id} value={p.id}>{p.name} · {p.capacityOz} oz · {p.category}</option>)}</select></label>
        <label>Stock type<select disabled={!canEdit || busy} value={entry.stockKind} onChange={e=>change(i,{stockKind:e.target.value as TapEntry["stockKind"],method:e.target.value==="backup" ? "full_backups" : "measured_ounces",remaining:0})}><option value="tap">Tapped stock</option><option value="backup">Full backups</option></select></label>
        <label>Observation method<select disabled={!canEdit || busy} value={entry.method} onChange={e=>change(i,{method:e.target.value as TapEntry["method"],remaining:0})}>{entry.stockKind==="backup" ? <option value="full_backups">Full keg count</option> : <><option value="measured_ounces">Measured remaining ounces</option><option value="estimated_fraction">Observed fraction, estimated</option></>}</select></label>
        <label>{entry.method==="full_backups" ? "Number of full kegs" : entry.method==="estimated_fraction" ? "Fraction remaining (0 to 1)" : "Remaining ounces"}<input disabled={!canEdit || busy} type="number" min="0" step={entry.method==="full_backups" ? "1" : "0.001"} max={entry.method==="estimated_fraction" ? "1" : undefined} value={entry.remaining} onChange={e=>change(i,{remaining:Number(e.target.value)})}/></label>
        <label>Measurement note<input disabled={!canEdit || busy} value={entry.note ?? ""} onChange={e=>change(i,{note:e.target.value})}/></label>{canEdit && <button className="lq-btn" disabled={busy} onClick={()=>{setEntries(entries.filter((_,j)=>j!==i));setReview(false);}}>Remove row</button>}
      </fieldset>)}
      {canEdit && <><button className="lq-btn" disabled={busy} onClick={()=>{setEntries([...entries,blank()]);setReview(false);}}>Add stock location</button><button className="lq-btn" disabled={busy || reason.trim().length<3} onClick={()=>work(async()=>{const saved=await saveTapObservation(open.id,open.revision,entries,reason,open.status==="submitted");edit(saved);})}>{open.status==="submitted" ? "Save audited correction" : "Save draft"}</button></>}
      {open.status==="draft" && canCount && <><button className="lq-btn" disabled={busy || !entries.length} onClick={()=>setReview(true)}>Review before submit</button>{review && <div><p>{entries.length} locations. Save the final observations before submitting. After submit, corrections retain an audited version.</p><button className="lq-btn" disabled={busy || reason.trim().length<3} onClick={()=>work(async()=>{const saved=await saveTapObservation(open.id,open.revision,entries,reason);setOpen(saved);const submitted=await submitTapObservation(saved.id,saved.revision,reason);edit(submitted);})}>Save and submit</button></div>}</>}
    </div>}
    {canManage && data && <details className="lq-bv-card"><summary>Review a tap and package mapping</summary><p>Use the exact GoTab transaction name and zone. Confirm package capacity and the number of physical count units in one keg from supplier evidence. New mappings take effect at the date entered; historical mappings stay readable.</p>
      <label>Product name<input value={mapping.name} onChange={e=>setMapping({...mapping,name:e.target.value})}/></label><label>Invoice inventory item<select value={mapping.skuId} onChange={e=>setMapping({...mapping,skuId:e.target.value})}><option value="">Choose…</option>{data.items.filter(s=>s.cogsBucket==="beer_draft" || s.cogsBucket==="wine").map(s=><option key={s.id} value={s.id}>{s.name} · {s.unitLabel ?? s.countUnit}</option>)}</select></label>
      <label>Category<select value={mapping.category} onChange={e=>setMapping({...mapping,category:e.target.value as "beer"|"wine"})}><option value="beer">Draft beer</option><option value="wine">Kegged wine</option></select></label>
      <label>Confirmed keg capacity, ounces<input type="number" min="0.001" value={mapping.capacityOz} onChange={e=>setMapping({...mapping,capacityOz:e.target.value})}/></label><label>Confirmed physical count units in one keg<input type="number" min="0.001" value={mapping.countUnitsPerKeg} onChange={e=>setMapping({...mapping,countUnitsPerKeg:e.target.value})}/></label>
      <label>Exact GoTab transaction name<input value={mapping.transactionName} onChange={e=>setMapping({...mapping,transactionName:e.target.value})}/></label><label>Exact GoTab zone ID (blank if absent)<input value={mapping.zoneId} onChange={e=>setMapping({...mapping,zoneId:e.target.value})}/></label><label>Exact backup keg name<input value={mapping.backupName} onChange={e=>setMapping({...mapping,backupName:e.target.value})}/></label><label>Effective from, UTC<input type="datetime-local" value={mapping.effectiveFrom} onChange={e=>setMapping({...mapping,effectiveFrom:e.target.value})}/></label><label><input type="checkbox" checked={mapping.active} onChange={e=>setMapping({...mapping,active:e.target.checked})}/> Active (clear to retire this tap identity from this date)</label>
      <button className="lq-btn" disabled={busy || reason.trim().length<3} onClick={()=>work(()=>addTapPackage({...mapping,productId:"18468666",capacityOz:Number(mapping.capacityOz),countUnitsPerKeg:Number(mapping.countUnitsPerKeg),zoneId:mapping.zoneId || null,effectiveFrom:new Date(`${mapping.effectiveFrom}:00Z`).toISOString(),reason}))}>Save reviewed mapping</button>
    </details>}
    <label><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/> Show original report versions</label>{(history ? rows : latest).map(r=><BeverageReportView key={r.id} row={r}/>)}
  </section>;
}
