import { gatedJson } from "./api";
export interface TapPackage { id:string;revision:number;name:string;skuId:string;category:"beer"|"wine";capacityOz:number;countUnitsPerKeg:number;countUnit:string;unitLabel:string|null;transactionName:string;zoneId:string|null;productId:string;effectiveFrom:string;backupName:string;active:boolean }
export interface TapStock { key:string;stockKind:"backup"|"tap";package:TapPackage;remainingOz:number;method:"full_backups"|"measured_ounces"|"estimated_fraction";costPerKegCents:number|null;costBasis:string;note:string|null }
export interface TapObservation { id:string;revision:number;observedAt:string;status:"draft"|"submitted";lines:TapStock[];countedBy:string;submittedAt:string|null;boundaryCountSessionId?:string|null;samePhysicalWalkConfirmed?:boolean }
export interface TapEntry {key:string;stockKind:"backup"|"tap";packageId:string;remaining:number;method:TapStock["method"];note?:string|null}
export interface BeverageReport {id:string;scope:"liquor"|"packaged_beer"|"tap_measured"|"draft_estimate";closingId:string;openingId:string|null;version:number;reason:string;createdAt:string;report:{baseline:boolean;provisional:boolean;reasons:string[];knownCogsCents:number;completeCogsCents:number|null;salesCents:number|null;periodStart?:string|null;periodEnd?:string;start?:string|null;end?:string;componentPct?:number|null;cogsPct?:number|null;estimated?:boolean;residualUncertainty?:string|null;items?:{skuId:string;name:string;cogsCents:number|null;reasons:string[]}[];lines?:{skuId:string;name:string;openingOz:number|null;receivedOz:number|null;closingOz:number|null;actualUsedOz:number|null;pouredOz:number;lossOz:number|null;salesCents:number;cogsCents:number|null;reasons:string[]}[];unmappedSales?:{name:string|null;zoneId:string|null;ounces:number;cents:number}[];kitchenProduce?:{reportId:string;version:number;cogsCents:number|null;reasons?:string[];basis?:{policy:string;opening:{foodCountId:string;submittedAt:string;linkRevision:number};closing:{foodCountId:string;submittedAt:string;linkRevision:number};accountingStart:string;accountingEnd:string}}|null}}
export interface BeverageCount {id:string;submittedAt:string|null;isFullCount:boolean}
export interface BeverageCostData { reports:BeverageReport[];counts:{liquor:BeverageCount[];packaged_beer:BeverageCount[]};allIn:{periodStart:string|null;periodEnd:string;cogsCents:number|null;salesCents:number|null;pct:number|null;targetPct:number;reasons:string[];sources:{liquor:string;beer:string|null;tap:string|null;kitchenProduce:string|null}}[] }
export interface TapData {packages:TapPackage[];observations:TapObservation[];reports:BeverageReport[];counts:{id:string;startedAt:string;submittedAt:string|null;status:string;countedBy:string}[];items:{id:string;name:string;countUnit:string;unitLabel:string|null;cogsBucket:string|null}[]}
const json=(body:unknown)=>({headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
export const getBeverageCost=()=>gatedJson<BeverageCostData>("/admin/bar/beverage-cost");
export const rerunBeverageCost=(id:string,scope:"liquor"|"packaged_beer",reason:string)=>gatedJson(`/admin/bar/beverage-cost/${id}/rerun`,{method:"POST",...json({scope,reason})});
export const getBeverageValues=(id:string)=>gatedJson<{lines:{name:string;line:{id:string;qtyUnits:string;countUnitAtCount:string|null;unitCostAtCount:string|null}}[];overrides:{lineId:string;revision:number;cost:string}[];batch:{lines:{skuId:string;name:string;qty:number;countUnit:string|null;cost:number|null}[];concerns:string[]}|null;batchOverride:{revision:number;costs:Record<string,number>}|null}>(`/admin/bar/beverage-cost/${id}/values`);
export const revalueBeverage=(id:string,reason:string,changes:{lineId:string;revision:number;cost:number}[],batch?:{batchRevision:number;batchChanges:{skuId:string;cost:number}[]})=>gatedJson(`/admin/bar/beverage-cost/${id}/revalue`,{method:"POST",...json({reason,changes,...batch})});
export const getTapInventory=()=>gatedJson<TapData>("/admin/bar/tap-inventory");
export const addTapPackage=(body:Omit<TapPackage,"id"|"revision"|"countUnit"|"unitLabel">&{reason:string})=>gatedJson("/admin/bar/tap-packages",{method:"POST",...json(body)});
export const startTapObservation=(body:{boundaryCountSessionId?:string|null;samePhysicalWalkConfirmed?:boolean}={})=>gatedJson<TapObservation>("/admin/bar/tap-observations",{method:"POST",...json(body)});
export const saveTapObservation=(id:string,revision:number,lines:TapEntry[],reason:string,correct=false)=>gatedJson<TapObservation>(`/admin/bar/tap-observations/${id}${correct ? "/correct" : ""}`,{method:correct ? "POST" : "PUT",...json({revision,lines,reason})});
export const submitTapObservation=(id:string,revision:number,reason:string)=>gatedJson<TapObservation>(`/admin/bar/tap-observations/${id}/submit`,{method:"POST",...json({revision,reason})});
export const computeTapReport=(id:string,scope:"tap_measured"|"draft_estimate",reason:string)=>gatedJson(`/admin/bar/tap-observations/${id}/report`,{method:"POST",...json({scope,reason})});
export interface ConsumableRecipe {productId:string;revision:number;basis:string;lines:{skuId:string;qty:number;unit:string}[];cost:{knownCents:number;completeCents:number|null;missing:string[]}}
export interface ConsumableData {recipes:ConsumableRecipe[];items:{id:string;name:string;countUnit:string;recipeUnit:string|null}[]}
export const getConsumableRecipes=()=>gatedJson<ConsumableData>("/admin/bar/consumable-recipes");
export const saveConsumableRecipe=(productId:string,body:{revision:number;reason:string;basis:string;lines:ConsumableRecipe["lines"]})=>gatedJson(`/admin/bar/consumable-recipes/${encodeURIComponent(productId)}`,{method:"PUT",...json(body)});
export interface KitchenBoundaryWalk {id:string;countedBy:string;startedAt:string;submittedAt:string;section:string;isFullCount:boolean;status:string}
export interface KitchenBoundaryData {foodCounts:KitchenBoundaryWalk[];barCounts:KitchenBoundaryWalk[];links:{barCountId:string;foodCountId:string;revision:number;active:boolean;reason:string;snapshot:{foodSubmittedAt:string;barSubmittedAt:string}}[];policy:string}
export const getKitchenBoundaries=()=>gatedJson<KitchenBoundaryData>("/admin/bar/kitchen-boundaries");
export const saveKitchenBoundary=(barId:string,body:{foodCountId:string;revision:number;confirmed:boolean;active:boolean;reason:string})=>gatedJson(`/admin/bar/kitchen-boundaries/${barId}`,{method:"POST",...json(body)});
